language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     
    - LUA=luajit2.1  # current head of 2.1 branch

install:
  - source .travis/setenv_lua.sh
  - luarocks install dkjson

script:
  - luarocks make lua-resty-certificate-sso-git-1.rockspec CFLAGS="-O2 -fPIC"

jobs:
  include:
    - stage: deploy
      env:
        - LUA=lua5.1
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .travis/deploy.sh
        on:
          repo: sidoh/lua-resty-certificate-sso
          tags: true
